FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Cài đặt các gói hệ thống cần thiết
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    ffmpeg \
    libasound2-dev \
    wget \
    libsdl2-dev libsdl2-2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Clone và build dự án whisper.cpp từ repo gốc
WORKDIR /opt/whisper.cpp
RUN git clone https://github.com/ggml-org/whisper.cpp.git . && \
    cmake -B build -DWHISPER_SDL2=ON && \
    cmake --build build --config Release

# Tạo thư mục models và tải model base
RUN mkdir -p models && \
    wget -O models/ggml-base.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin

# Chạy ứng dụng với model base
CMD ["./build/bin/whisper-stream", "-m", "models/ggml-base.bin", "-t", "8", "--step", "500", "--length", "5000"]
