[project]
name = "no-hands-no-problem"
version = "0.1.0"
description = "INT3011 project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyaudio>=0.2.14",
    "speechrecognition>=3.14.2",
]
